import React from 'react'
import Head from 'next/head'

import { useRouter } from 'next/router'
const success = () => {
  const routers = useRouter()
  return (
    <div>
      <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='pb-32 lg:px-10 gap-y-[300px] bg-[url("/bg-main-mobile.png")] bg-no-repeat h-screen bg-contain w-full relative bg-top px-3  md:bg-[url("/bg-main-desktop.png")]  md:bg-left flex flex-col md:flex-row justify-between'>
    <section className='lg:w-[45%] flex flex-col lg:justify-center lg:items-center h-[50%] md:h-[80%] md:gap-5 md:mt-24 md:w-[60%]'>
      <div className='lg:w-[80%] md:w-[70%] md:relative md:ml-5 w-[80%]  absolute z-10 md:top-0 sm:top-[30%] top-[25%]'>
          <div className=' text-White font-medium text-[20px]'>
            <div className='md:w-[23%] absolute top-[10%]  left-[10%]'>
              <img src='/card-logo.svg' className='object-cover w-full '/>
            </div>
                <p className=' font-medium lg:text-[20px] absolute top-[55%] left-[10%] md:text-sm text-[16px]'>{routers.query.card}</p>
                <p className=' text-sm absolute top-[75%] bottom-[25%] left-[10%]'>{routers.query.name}</p>
                <p className=' text-sm  absolute top-[75%] bottom-[25%] right-[10%]'>{routers.query.month} / {routers.query.year}</p>
          </div>
          <img src="/bg-card-front.png" className='object-cover w-full'/>
      </div>
      <div className='lg:w-[80%] lg:ml-52 md:w-[70%] md:ml-20 md:relative w-[80%] absolute top-[4%] right-[4%] md:right-0'>
          <p className='absolute text-sm bottom-[58%] top-[43%]  right-[10%] text-White font-medium '>{routers.query.cvc}</p>
          <img src="/bg-card-back.png" alt="card" className='object-cover w-full' />
      </div>
    </section >
    <section className=' md:mt-0 md:pr-10 px-6 py-10  mt-[80px] sm:mt-[200px] md:pt-[160px] bg-White lg:w-[40%] md:w-[40%] '>
        <div className='flex flex-col justify-center items-center gap-6'>
            <img src="/icon-complete.svg" alt="response"/>
            <h1 className='uppercase text-Verydarkviolet text-center font-medium text-lg  tracking-[6px]'>thank you</h1>
            <p className='text-Darkgrayishviolet text-sm text-center'>we've added your card details</p>
            <button type="button" className='w-[60%] text-white bg-Verydarkviolet text-White p-2 rounded md:w-[70%] text-md'>Continue</button>
        </div>
    </section>
  </main>
    </div>
    
  )
}

export default success